// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/config/filter/http/modsec/v2/modsec.proto

package ModSecurity_envoy

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Remote with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Remote) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Remote with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RemoteMultiError, or nil if none found.
func (m *Remote) ValidateAll() error {
	return m.validate(true)
}

func (m *Remote) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for Url

	if len(errors) > 0 {
		return RemoteMultiError(errors)
	}
	return nil
}

// RemoteMultiError is an error wrapping multiple validation errors returned by
// Remote.ValidateAll() if the designated constraints aren't met.
type RemoteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoteMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoteMultiError) AllErrors() []error { return m }

// RemoteValidationError is the validation error returned by Remote.Validate if
// the designated constraints aren't met.
type RemoteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoteValidationError) ErrorName() string { return "RemoteValidationError" }

// Error satisfies the builtin error interface
func (e RemoteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemote.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoteValidationError{}

// Validate checks the field values on Decoder with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Decoder) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Decoder with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DecoderMultiError, or nil if none found.
func (m *Decoder) ValidateAll() error {
	return m.validate(true)
}

func (m *Decoder) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRemotes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DecoderValidationError{
						field:  fmt.Sprintf("Remotes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DecoderValidationError{
						field:  fmt.Sprintf("Remotes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DecoderValidationError{
					field:  fmt.Sprintf("Remotes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for RemotesOverwriteOnSuccess

	if len(errors) > 0 {
		return DecoderMultiError(errors)
	}
	return nil
}

// DecoderMultiError is an error wrapping multiple validation errors returned
// by Decoder.ValidateAll() if the designated constraints aren't met.
type DecoderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DecoderMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DecoderMultiError) AllErrors() []error { return m }

// DecoderValidationError is the validation error returned by Decoder.Validate
// if the designated constraints aren't met.
type DecoderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DecoderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DecoderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DecoderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DecoderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DecoderValidationError) ErrorName() string { return "DecoderValidationError" }

// Error satisfies the builtin error interface
func (e DecoderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDecoder.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DecoderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DecoderValidationError{}
