// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.18.0
// source: envoy/config/filter/http/modsec/v2/modsecurity_filter.proto

// package modsecurity.filter;

package envoy_extensions_filters_http_modsecurity_v1

import (
	_ "github.com/cncf/xds/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// [#next-free-field: 5]
type ModSecurity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If set, rules are loaded from this path
	RulesPath string `protobuf:"bytes,1,opt,name=rules_path,json=rulesPath,proto3" json:"rules_path,omitempty"`
	// If set, rules are loaded from this inline configuration.
	// Note, if both rules_path and rules_inline are set, rules_path is first loaded and afterwards rules_inline is loaded
	RulesInline string `protobuf:"bytes,2,opt,name=rules_inline,json=rulesInline,proto3" json:"rules_inline,omitempty"`
}

func (x *ModSecurity) Reset() {
	*x = ModSecurity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModSecurity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModSecurity) ProtoMessage() {}

func (x *ModSecurity) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModSecurity.ProtoReflect.Descriptor instead.
func (*ModSecurity) Descriptor() ([]byte, []int) {
	return file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescGZIP(), []int{0}
}

func (x *ModSecurity) GetRulesPath() string {
	if x != nil {
		return x.RulesPath
	}
	return ""
}

func (x *ModSecurity) GetRulesInline() string {
	if x != nil {
		return x.RulesInline
	}
	return ""
}

// [#next-free-field: 4]
type PerRouteConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to DisableOptions:
	//	*PerRouteConfig_Disable
	//	*PerRouteConfig_DisableRequest
	//	*PerRouteConfig_DisableResponse
	DisableOptions isPerRouteConfig_DisableOptions `protobuf_oneof:"disable_options"`
}

func (x *PerRouteConfig) Reset() {
	*x = PerRouteConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerRouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerRouteConfig) ProtoMessage() {}

func (x *PerRouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerRouteConfig.ProtoReflect.Descriptor instead.
func (*PerRouteConfig) Descriptor() ([]byte, []int) {
	return file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescGZIP(), []int{1}
}

func (m *PerRouteConfig) GetDisableOptions() isPerRouteConfig_DisableOptions {
	if m != nil {
		return m.DisableOptions
	}
	return nil
}

func (x *PerRouteConfig) GetDisable() bool {
	if x, ok := x.GetDisableOptions().(*PerRouteConfig_Disable); ok {
		return x.Disable
	}
	return false
}

func (x *PerRouteConfig) GetDisableRequest() bool {
	if x, ok := x.GetDisableOptions().(*PerRouteConfig_DisableRequest); ok {
		return x.DisableRequest
	}
	return false
}

func (x *PerRouteConfig) GetDisableResponse() bool {
	if x, ok := x.GetDisableOptions().(*PerRouteConfig_DisableResponse); ok {
		return x.DisableResponse
	}
	return false
}

type isPerRouteConfig_DisableOptions interface {
	isPerRouteConfig_DisableOptions()
}

type PerRouteConfig_Disable struct {
	Disable bool `protobuf:"varint,1,opt,name=disable,proto3,oneof"`
}

type PerRouteConfig_DisableRequest struct {
	DisableRequest bool `protobuf:"varint,2,opt,name=disable_request,json=disableRequest,proto3,oneof"`
}

type PerRouteConfig_DisableResponse struct {
	DisableResponse bool `protobuf:"varint,3,opt,name=disable_response,json=disableResponse,proto3,oneof"`
}

func (*PerRouteConfig_Disable) isPerRouteConfig_DisableOptions() {}

func (*PerRouteConfig_DisableRequest) isPerRouteConfig_DisableOptions() {}

func (*PerRouteConfig_DisableResponse) isPerRouteConfig_DisableOptions() {}

var File_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto protoreflect.FileDescriptor

var file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x6d, 0x6f, 0x64, 0x73, 0x65,
	0x63, 0x2f, 0x76, 0x32, 0x2f, 0x6d, 0x6f, 0x64, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2c, 0x65,
	0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x6d, 0x6f, 0x64,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x75, 0x64, 0x70,
	0x61, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x49, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x0f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0e,
	0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b,
	0x0a, 0x10, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0f, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x0a, 0x0f, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x58,
	0x0a, 0x3a, 0x69, 0x6f, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x6d, 0x6f,
	0x64, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x42, 0x10, 0x4d, 0x6f,
	0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0xba, 0x80, 0xc8, 0xd1, 0x06, 0x02, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescOnce sync.Once
	file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescData = file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDesc
)

func file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescGZIP() []byte {
	file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescOnce.Do(func() {
		file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescData)
	})
	return file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDescData
}

var file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_goTypes = []interface{}{
	(*ModSecurity)(nil),    // 0: envoy.extensions.filters.http.modsecurity.v1.ModSecurity
	(*PerRouteConfig)(nil), // 1: envoy.extensions.filters.http.modsecurity.v1.PerRouteConfig
}
var file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_init() }
func file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_init() {
	if File_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModSecurity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerRouteConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PerRouteConfig_Disable)(nil),
		(*PerRouteConfig_DisableRequest)(nil),
		(*PerRouteConfig_DisableResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_goTypes,
		DependencyIndexes: file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_depIdxs,
		MessageInfos:      file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_msgTypes,
	}.Build()
	File_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto = out.File
	file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_rawDesc = nil
	file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_goTypes = nil
	file_envoy_config_filter_http_modsec_v2_modsecurity_filter_proto_depIdxs = nil
}
