// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/config/filter/http/modsec/v2/modsecurity_filter.proto

package envoy_extensions_filters_http_modsecurity_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ModSecurity with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ModSecurity) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for RulesPath

	// no validation rules for RulesInline

	return nil
}

// ModSecurityValidationError is the validation error returned by
// ModSecurity.Validate if the designated constraints aren't met.
type ModSecurityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModSecurityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModSecurityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModSecurityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModSecurityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModSecurityValidationError) ErrorName() string { return "ModSecurityValidationError" }

// Error satisfies the builtin error interface
func (e ModSecurityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModSecurity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModSecurityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModSecurityValidationError{}

// Validate checks the field values on PerRouteConfig with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PerRouteConfig) Validate() error {
	if m == nil {
		return nil
	}

	switch m.DisableOptions.(type) {

	case *PerRouteConfig_Disable:
		// no validation rules for Disable

	case *PerRouteConfig_DisableRequest:
		// no validation rules for DisableRequest

	case *PerRouteConfig_DisableResponse:
		// no validation rules for DisableResponse

	}

	return nil
}

// PerRouteConfigValidationError is the validation error returned by
// PerRouteConfig.Validate if the designated constraints aren't met.
type PerRouteConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PerRouteConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PerRouteConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PerRouteConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PerRouteConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PerRouteConfigValidationError) ErrorName() string { return "PerRouteConfigValidationError" }

// Error satisfies the builtin error interface
func (e PerRouteConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPerRouteConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PerRouteConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PerRouteConfigValidationError{}
